import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ImageWrapper from "../components/ImageWrapper/ImageWrapper";

export default function Home() {
  const [searchString, setSearchString] = useState('Car');
  const [alignment, setAlignment] = useState('center');

  const handleClick = async (e) => {
    e.preventDefault()
    setSearchString(e.target.search.value);
    setAlignment(e.target.alignment.value);
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Image Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="bg-white container mx-auto">
          <div className="pt-6">
            <div className="mx-auto max-w-2xl px-4 pt-10 pb-16 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-1 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:px-8 lg:pt-16 lg:pb-24">
              <div className="lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
                <h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">
                  Next Image Gallery
                </h1>
                <form onSubmit={handleClick} className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                <div class="mb-4">
                  <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="search">Search for a term using a search term (eg: Car)</label>
                </div>
                <div class="mb-6">
                  <input type="text" id="search" name="fisearchrst" placeholder="enter search term ('car')" className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" />
                </div>
                <div class="mb-4">
                  <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="search">Alignment</label>
                </div>
                <div className="mb-6 relative">
                  <select class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="alignment">
                    <option>center</option>
                    <option>left</option>
                    <option>right</option>
                    <option>left-top</option>
                    <option>top</option>
                    <option>right-top</option>
                    <option>left-bottom</option>
                    <option>bottom</option>
                    <option>right-bottom</option>
                  </select>
                  <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                    <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">Submit</button>
                </div>
                </form>
              </div>
            </div>
            <div className="mx-auto mt-6 max-w-2xl sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:gap-x-8 lg:px-8">
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                  <h2 className="text-xl font-bold">Hero {alignment}</h2>
              </div>
            </div>  
            <div className="mx-auto mt-6 max-w-2xl sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-1 lg:gap-x-8 lg:px-8">
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                <ImageWrapper source={searchString} hero alignment={alignment}/>
              </div>
            </div>
            <div className="mx-auto mt-6 max-w-2xl sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:gap-x-8 lg:px-8">
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                  <h2 className="text-xl font-bold">Video {alignment}</h2>
              </div>
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                <h2 className="text-xl font-bold">Picture {alignment}</h2>
              </div>
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                <h2 className="text-xl font-bold">Square {alignment}</h2>
              </div>
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                <h2 className="text-xl font-bold">Portrait {alignment}</h2>
              </div>
            </div>
            <div className="mx-auto mt-6 max-w-2xl sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:gap-x-8 lg:px-8">
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                  <ImageWrapper source={searchString} video alignment={alignment}/>
              </div>
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                  <ImageWrapper source={searchString} picture alignment={alignment}/>
              </div>
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                  <ImageWrapper source={searchString} square alignment={alignment}/>
              </div>
              <div className="lg:grid lg:grid-cols-1 lg:gap-y-8">
                  <ImageWrapper source={searchString} portrait alignment={alignment}/>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
